# Generated by Django 6.0.4 on 2026-04-30 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_phase10_attachments_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='decision',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_review', 'В работе'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='new', max_length=20),
        ),
    ]
