# Generated by Django 6.0.4 on 2026-04-30 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='hidden_from_feed',
            field=models.BooleanField(default=False, help_text='Не показывается в /social/feed/; в ленте сообщества остаётся.', verbose_name='скрыто из общей ленты'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='media.uploadedfile', verbose_name='вложение'),
        ),
    ]
