target-version = "py313"
line-length = 100
src = ["."]

[lint]
select = ["E", "F", "I", "W"]
ignore = []

[lint.per-file-ignores]
"config/settings/*.py" = ["F405", "F403"]
"**/migrations/*.py" = ["E501"]
