# Generated by Django 6.0.4 on 2026-04-24 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='о себе')),
                ('avatar', models.URLField(blank=True, verbose_name='аватар URL')),
                ('locale', models.CharField(default='ru', max_length=10, verbose_name='локаль')),
                ('privacy', models.CharField(choices=[('public', 'Публичный'), ('private', 'Только я')], default='public', max_length=20, verbose_name='приватность')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, verbose_name='раскладка дашборда')),
                ('default_landing', models.CharField(blank=True, max_length=64, verbose_name='лендинг по умолчанию')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
