# Generated by Django 6.0.4 on 2026-04-30 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='console.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='console.organization')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
                'ordering': ('organization_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('permission_slugs', models.JSONField(blank=True, default=list, help_text='Список кодов из каталога разрешений консоли.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='permission_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'группа пользователей (права)',
                'verbose_name_plural': 'группы пользователей (права)',
                'ordering': ('name',),
            },
        ),
    ]
