# Generated by Django 6.0.4 on 2026-04-30 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCounterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(blank=True, default='', max_length=80, verbose_name='slug')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'контрагент (работа)',
                'verbose_name_plural': 'контрагенты (работа)',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='workcolumn',
            name='semantic',
            field=models.CharField(blank=True, choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('review', 'Проверка'), ('paused', 'На паузе'), ('done', 'Сделано'), ('released', 'Релиз'), ('cancelled', 'Отменено'), ('backlog', 'Бэклог'), ('development', 'Разработка'), ('testing', 'Тестирование')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='WorkContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='имя')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='work.workcounterparty')),
            ],
            options={
                'verbose_name': 'контакт (работа)',
                'verbose_name_plural': 'контакты (работа)',
                'ordering': ('name',),
            },
        ),
    ]
