# Generated by Django 6.0.4 on 2026-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='Доступ к /work и задачам; выставляет администратор.', verbose_name='сотрудник (рабочий контур)'),
        ),
    ]
