# Generated by Django 6.0.4 on 2026-04-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_kind',
            field=models.CharField(blank=True, choices=[('internal', 'Штат'), ('partner', 'Партнёр')], default='', help_text='internal/partner для сотрудников; пусто для обычных пользователей.', max_length=20, verbose_name='тип занятости'),
        ),
    ]
