# Generated by Django 6.0.4 on 2026-04-30 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_employment_kind'),
        ('console', '0002_org_groups_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='console.department', verbose_name='отдел'),
        ),
    ]
