# Generated by Django 6.0.4 on 2026-04-24 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts_authored', to=settings.AUTH_USER_MODEL)),
                ('wall_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пост на стене',
                'verbose_name_plural': 'посты на стенах',
                'ordering': ('-created_at',),
            },
        ),
    ]
