# Generated by Django 6.0.4 on 2026-04-30 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='hidden_from_feed',
            field=models.BooleanField(default=False, help_text='Пост остаётся на стене, но не попадает в /social/feed/.', verbose_name='скрыто из общей ленты'),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_posts', to='media.uploadedfile', verbose_name='вложение'),
        ),
    ]
