"""Каталог разрешений для групп пользователей (консоль / внутренние инструменты)."""

PERMISSION_CATALOG: list[dict[str, str]] = [
    {"slug": "console.view_users", "name": "Просмотр пользователей"},
    {"slug": "console.edit_users", "name": "Редактирование пользователей и ролей"},
    {"slug": "console.view_audit", "name": "Просмотр журнала аудита"},
    {"slug": "console.manage_groups", "name": "Управление группами и разрешениями"},
    {"slug": "console.manage_org", "name": "Управление компаниями и отделами"},
    {"slug": "console.moderate_communities", "name": "Модерация сообществ из консоли"},
    {"slug": "internal.tools", "name": "Доступ к внутренним инструментам (по политике продукта)"},
    {"slug": "internal.metrics.read", "name": "Чтение внутренних метрик"},
    {"slug": "work.advanced", "name": "Расширенные возможности рабочего контура"},
    {"slug": "work.dashboard.read", "name": "Просмотр рабочего дашборда"},
    {"slug": "work.group.read", "name": "Просмотр рабочих групп"},
    {"slug": "work.group.write", "name": "Управление рабочими группами"},
    {"slug": "work.board.read", "name": "Просмотр досок"},
    {"slug": "work.board.write", "name": "Управление досками"},
    {"slug": "work.column.read", "name": "Просмотр колонок"},
    {"slug": "work.column.write", "name": "Управление колонками и порядком"},
    {"slug": "work.task.read", "name": "Просмотр задач"},
    {"slug": "work.task.write", "name": "Управление задачами"},
    {"slug": "messaging.read", "name": "Чтение сообщений"},
    {"slug": "messaging.write", "name": "Отправка и создание диалогов"},
    {"slug": "social.read", "name": "Просмотр social-функций"},
    {"slug": "social.write", "name": "Изменение social-данных"},
    {"slug": "media.upload", "name": "Загрузка медиа"},
    {"slug": "profiles.read", "name": "Просмотр профилей"},
    {"slug": "profiles.self.read", "name": "Просмотр своего профиля"},
    {"slug": "profiles.self.write", "name": "Редактирование своего профиля"},
    {"slug": "moderation.report.write", "name": "Создание жалоб на контент"},
    {"slug": "moderation.queue.read", "name": "Просмотр очереди модерации"},
    {"slug": "moderation.queue.write", "name": "Обработка жалоб модерации"},
    {"slug": "notifications.read", "name": "Просмотр уведомлений"},
    {"slug": "notifications.write", "name": "Изменение статуса уведомлений"},
]

ALL_PERMISSION_SLUGS: frozenset[str] = frozenset(p["slug"] for p in PERMISSION_CATALOG)
